### ISSUE TITLE
Replace EULA with OSL

### ISSUE THREAD

**Issue by IvanChepurnyi** [EcomDev/checkitout#1]
In all PHP file headers, we need to replace EULA with OSL, as project got open sourced.

**Comment by IvanChepurnyi** [comment]
@andrewhowdencom can you take care of this?

**Comment by andrewhowdencom** [comment]
Should have a PR up in around 12 hours or so.

**Comment by andrewhowdencom** [comment]
[Initial commit complete](https://github.com/andrewhowdencom/checkitout/commit/ad29510747df7a85af262dcd2a1fb183064c5bde), going to take another look at it after dinner and then create the pull. Running a little later than I'd hoped.

**Comment by IvanChepurnyi** [comment]
Thank you @andrewhowdencom!
