### ISSUE TITLE
coupon codes are removed from quote when shipping to billing address

### ISSUE THREAD

**Issue by jdukeukpos** [EcomDev/checkitout#11]
When Mage_Checkout_Model_Type_Onepage::saveBilling() is called by EcomDev_CheckItOut_Model_Type_Onepage:: saveBilling() the following fields are copied from the billing address to the shipping address when "ship to billing" is selected:
cached_items_all
cached_items_nominal
cached_items_nonnominal

These are fields which cache the product items associated with the address and in the case of the billing address there are none associated (unless virtual)

When present, but empty, on the billing address and then copied onto the shipping address the shipping address then has no product items associated it.

This means that Mage_SalesRule_Model_Quote_Discount::collect() then applies no discounts and then Mage_Sales_Model_Quote::_validateCouponCode() removed the coupon from the quote.

I suggest adding the following code in EcomDev_CheckItOut_Model_Type_Onepage::saveBilling():

--> fix code
        if (!$this->getQuote()->isVirtual() && !empty($data['use_for_shipping']) ) {
            $_billing=$this->getQuote()->getBillingAddress();
            $_billing->unsetData('cached_items_all');
            $_billing->unsetData('cached_items_nominal');
            $_billing->unsetData('cached_items_nonnominal');
        }
<-- end -  fix code

// existing code
        $result = $this->_getDependency()->saveBilling($data, $customerAddressId);

..
..

**Comment by andrewhowdencom** [comment]
This should be resolved by https://github.com/EcomDev/checkitout/pull/14. Can you confirm, @jdukeukpos?

**Comment by andrewhowdencom** [comment]
Closing as it should have been resolved; fixed by @arollason.
